version: '3.1'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: 'admin'
    # volumes: # data persistance
    #   - ./db-data/:/var/lib/postgresql/data/
